import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/shared/Navbar";
import Footer from "../components/shared/Footer";
import AuthProvider from "../Provider/AuthProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Binary Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <Navbar></Navbar>
          <div className="min-h-screen">
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </AuthProvider>

  );
}
